syntax = "proto3";

option java_package = "ru.terentyev.d_dating_profiles.proto";
option java_multiple_files = true;

message Profile {
    string id = 1;
    string name = 2;
    int32 age = 3;
    string description = 4;
    bool male = 5;
    repeated Photo photos = 6;
    repeated Hobby hobbies = 7;
    Purpose purpose = 8;
    repeated Match matches = 9;
    string email = 10;
}

message Photo {
    string id = 1;
    Profile owner = 2;
    string url = 3;
    int32 order = 4;
}

message Swipe {
    Profile person1 = 1;
    Profile person2 = 2;
    bool choiceOf1 = 3;
    bool choiceOf2 = 4;
}

message Match {
    Profile person1 = 1;
    Profile person2 = 2;
    repeated Message dialog = 3;
}

message Message {
    string id = 1;
    Profile who = 2;
    Profile whom = 3;
    string text = 4;
    int32 position = 5;
}

message ProfileSettings {
    bool showBothGenders = 2;
    bool showMale = 3;
    int32 desiredAgeMin = 4;
    int32 desiredAgeMax = 5;
}

enum Hobby {
    TENNIS = 0;
    BILLIARDS = 1;
    IT = 2;
    MUSIC = 3;
    TRAVELING = 4;
}

enum Purpose {
     FRIENDSHIP = 0;
     LOVE = 1;
     FREE_LOVE = 2;
     EVERYTHING = 3;
     DONT_KNOW = 4;
}